- .kokoro/continuous/node8/test.cfg
- .kokoro/presubmit/node8/test.cfg
- .kokoro/test.sh
I'll add kokoro tests back after getting the token for uploading to codecov.io (and kokoro access to the token) set up.
After this change, kokoro tests should pass, I'll add the webhook to this repo.
> chore: remove code coverage reporting from kokoro tests

- package-lock.json
- package.json
- ts/third_party/cloud-debug-nodejs/src/agent/io/scanner.ts
It turns out that the code calling `lodash.pickyBy` was unreachable. `parse-duration` was unused in this module.
> cleanup: remove some unnecessary deps.

- .gitignore
- .kokoro/continuous/system_test.cfg
- .kokoro/presubmit/system_test.cfg
- README.md
- package-lock.json
- package.json
- system-test/busybench/package.json
- system-test/busybench/src/busybench.ts
- system-test/busybench/tsconfig.json
- system-test/system_test.go
- system-test/system_test.sh
Set up initial system tests for pprof-nodejs. 
Tested:
Looked at system test output logs to confirm expected version of Node is used. 
Locally ran validate that v8-canary test will run once kokoro configs are setup for it.
System tests which test the SourceMapper will be in a follow-up change.
> chore: add system tests

- package.json
- tools/publish.sh
Release notes: https://github.com/google/pprof-nodejs/releases/tag/untagged-342009bae76f787b1e1a
After this PR is in, I plan to trigger the release workflow. 
I don't expect that the workflow for publishing will be successful initially, but I feel that being able to try out the release workflow will be the quickest way to debug any issues.
I've updated the publishing script to tag the release as an alpha release (and the version is an alpha version), so if a version is released, it won't be downloaded unless this version is specifically requested.
> v0.2.0-alpha

- package.json
- tools/build/linux_build_and_test.sh
This allows node-pre-gyp to find the binaries.
> fix: publish binaries to GCS bucket location referenced in package.json

- .circleci/config.yml
- package.json
- tools/publish.sh
Release notes: https://github.com/google/pprof-nodejs/releases/edit/untagged-3573aa9fd72d459d0c05
This change also remove the release process using circle CI. Right now, to release, one must manually trigger the kokoro release workflow after adding a commit to bump the version.
Precompile binaries were tested with cloud-profiler-nodejs here: https://github.com/googleapis/cloud-profiler-nodejs/pull/442 (logs [here](https://sponge.corp.google.com/target?id=855415d8-8510-4307-a92e-5faf77c970ac&target=cloud-profiler%2Fnodejs-agent%2Fpresubmit%2Fpresubmit&searchFor=)).
> v0.2.0; release agent with pre-compiled binaries

- system-test/system_test.sh
- tools/kokoro/system-test/continuous/linux-v8-canary.cfg
TESTED: Ran `RUN_ONLY_V8_CANARY=true sh system-test/system_test.sh ` and `sh system-test/system_test.sh`, and verified that output for expected versions of Node.JS appeared.
> chore: add config and update system-test to support running tests with v8-canary

- system-test/busybench/tsconfig.json
- tsconfig.json
Specifying `target` in the main tsconfig.json was not necessary to make system tests pass, but seemed prudent given the problem we had with the benchmark.
> fix: Specify target in tsconfig to fix Node 6 system test

- binding.gyp
Confirmed that warnings including "cast between incompatible function types" did not appear in the linux prebuild presubmit test.
> chore: silence deprecation warnings that appear with gcc 8

- .gitignore
- bindings/profiler.cc
- package-lock.json
- system-test/Dockerfile.linux
- system-test/busybench-js/package.json
- system-test/busybench-js/src/busybench.js
- system-test/system_test.sh
- system-test/test.sh
- ts/src/time-profiler-bindings.ts
- ts/src/time-profiler.ts
Testing:
I've run test.sh with Node 12.3.1 and the V8 canary build from 6/10/19 (with and without VERIFY_TIME_LINE_NUMBERS=true).
Also inspected time profiles from each of these runs:
Node 13, w/o detailed lines
Node 13 w/ detailed lines
Node 12 w/o detailed lines
Node 12 w/ detailed lines
> feat: allow collecting profiles with more accurate line numbers

- bindings/profiler.cc
This change should allow the continuous V8 canary test to pass again.
It will also make profiler.cc more resistant to deprecation warnings, since Nan will handle more of the differences between v8 versions.
> chore: Use Nan::Set and Nan::Get instead of v8 setter and getters

- package-lock.json
- package.json
- ts/src/heap-profiler-bindings.ts
- ts/src/heap-profiler.ts
- ts/src/index.ts
- ts/src/profile-encoder.ts
- ts/src/profile-serializer.ts
- ts/src/sourcemapper/sourcemapper.ts
- ts/src/time-profiler-bindings.ts
- ts/src/time-profiler.ts
- ts/test/profiles-for-tests.ts
- ts/test/test-heap-profiler.ts
- ts/test/test-profile-encoder.ts
- ts/test/test-profile-serializer.ts
- ts/test/test-time-profiler.ts
- ts/third_party/cloud-debug-nodejs/src/agent/io/scanner.ts
Updated version of gts then ran gts fix.
Supersedes #53
> chore(deps): update dependency gts to v1

- ts/src/index.ts
It is useful in dependent modules to be able to use the types.
Needed in https://github.com/v8/sampling-heap-profiler/pull/36
> feat: export more types

- .github/workflows/ci.yaml
Tested: Pushed this commit to my master branch; all tests pass.
https://github.com/nolanmar511/pprof-nodejs/actions/runs/62508944
The ci.yaml used here is the same as the [ci.yaml used in cloud-profiler-nodejs](https://github.com/googleapis/cloud-profiler-nodejs/blob/0db53e206aef8d1fc5494f0f3726e4831e12d071/.github/workflows/ci.yaml#L1), but with the "docs" check removed.
I believe the added GitHub workflow will start running as presubmit checks once this PR is submitted.
Tests with the following names will appear as presubmit checks (basing this on github workflow tests which appear for cloud-profiler-nodejs):
* ci / test-linux (8) (pull_request)
* ci / test-linux (10) (pull_request)
* ci / test-linux (12) (pull_request)
* ci / test-linux (13) (pull_request)
* ci / test-windows …
> chore: start running unit tests with GitHub workflows

- system-test/test.sh
- tools/build/build.sh
- tools/publish.sh
This change also starts using `npm pack --quiet`.
> chore: use `npm install --quiet` to reduce noise in Kokoro test/build outputs

- system-test/test.sh
This change also logs the pprof output to make failures easier to debug.
> chore: allow for range of line numbers in line number system test

- bindings/profiler.cc
Work around memory leak in V8 CPU profiler (https://bugs.chromium.org/p/v8/issues/detail?id=11051) by creating and destroying the CPU profiler each time a CPU profile is collected. 
BREAKING:
With this change, an error will now occur when one attempts to collect 2 CPU profiles in parallel. 
TESTED: Confirmed pprof-nodejs no longer had memory leak by running small express application with a version of pprof-nodejs without this change and with the currently release version. When running this application with Node 14 overnight, a memory leak was no longer apparent. I added log statements to confirm the fix is included when this native portion is compiled for Node 12.
Other potential consequences of this change:
* I expect both the overhead of CPU profiling and the time spent in calls to …
> fix!: re-create CPU profiler each time a CPU profile is collected to work around V8 CPU profiler memory leak.

- .github/workflows/ci.yaml
- system-test/Dockerfile.linux
- system-test/Dockerfile.node15-alpine
- system-test/system_test.sh
- system-test/test.sh
- tools/build/build.sh
This change will also result in Node 15 prebuilt binaries being released.
Two changes were made to testing as part of allowing tests with Node 15 to pass:
* `npm run clean` is called when the test script exits. This ensures there are no stale binaries or javascript generated from typescript when the next test starts.
* `nvm` is installed in `/bin` rather than `/root`. This is probably where is always should have been installed and eliminated permission issues during `npm install`. (I think the permission issues observed were related to `npm install` using a non-root user to run installation scripts combined with "/root" being the working directory).
> chore: Run tests with Node 15

- .github/workflows/ci.yaml
- README.md
This should be submitted only after the "master" branch has been renamed to "main".
> chore: reference main branch, instead of master branch

- package.json
- ts/test/test-heap-profiler.ts
A newer version of `@types/node` node is available. The type definition for the return type of `process.memoryUsage` was updated, so a few tests which stubbed this method also needed to be updated.
> chore(deps): update @types/node to v15

- .github/workflows/ci.yaml
- package-lock.json
- system-test/Dockerfile.node16-alpine
- system-test/system_test.sh
- tools/build/build.sh
Fixes https://github.com/google/pprof-nodejs/issues/171
> feat: add pre-built binaries and support for Node 16

- package.json
The `source-map` package (version 0.7.3) [doesn't work with node 18](https://github.com/mozilla/source-map/issues/454).
A workaround while waiting for the [new release](https://github.com/mozilla/source-map/issues/452) is to use the beta version, which I found some other folks like [`terser`](https://github.com/terser/terser/pull/1164) are doing.
This PR temporarily switches to `source-map` version 0.8.0-beta.0.
With this, the node 18 workflow tests are passing, but will continue to monitor the project's health at least for the next couple of weeks.
The kokoro tests need additional fixes separately.
> test: temporarily workaround node 18 source-map issue

- system-test/Dockerfile.node18-alpine
- system-test/test.sh
The system tests builds the source from a mounted volume in docker.
Somehow this is causing issues with node 18 which is likely related to permissions/ownership of users outside vs inside the docker container.
This PR clones (`cp -r`) the source to a fresh directory that is owned by the user inside the docker container before testing.
Also added docker image for node 18 alpine that also used in system test.
> test: fix system test failure in node 18

- package-lock.json
- package.json
- ts/src/profile-encoder.ts
- ts/src/sourcemapper/sourcemapper.ts
- ts/test/test-profile-encoder.ts
Replacing our modest usage of [pify](https://github.com/sindresorhus/pify) with [`Util.promisify()`](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original). The pify dependency was added in 1c0a542b2135884b4742b0b37b98287f3ff705e5 when node6 appears to have been supported; promisify was added in Node 8, so I assume that's why pify was used.
[Pify claims some benefits over promisify](https://github.com/sindresorhus/pify#how-is-this-different-from-nodejss-utilpromisify) but it doesn't seem that important for our usage.
> chore: replace pify with Util.promisify

- system-test/Dockerfile.linux
- system-test/Dockerfile.node-alpine
> test: fix kokoro system-test by forcing ipv4 in tests

- system-test/Dockerfile.linux
This fixes failures I was seeing in continuous Kokoro tests because stretch no longer appears to be available in deb.debian.org:
```
Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
404  Not Found [IP: 151.101.22.132 80]
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
404  Not Found [IP: 151.101.22.132 80]
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch …
```
> test: bump debian version in system test

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- proto/profile.d.ts
- proto/profile.js
- system-test/Dockerfile.linux
- system-test/Dockerfile.node10-alpine
- system-test/Dockerfile.node12-alpine
- system-test/Dockerfile.node14-alpine
- system-test/Dockerfile.node15-alpine
- system-test/Dockerfile.node16-alpine
- system-test/test.sh
- tools/build/Dockerfile.alpine
- ts/src/profile-serializer.ts
Note this is being merged into a new branch `v3.2.1-release` for a backport release, which starts at tag `v3.2.0`. I have cherry picked a few upgrades to fix security vulnerabilities and build issues.
```
npm audit fix --omit=dev
up to date, audited 87 packages in 2s
8 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
> chore: cherry pick security fixes for v3.2.1 backport [security]

- system-test/Dockerfile.linux
- tools/publish.sh
Update nvm and the NodeJS version it pulls in.
See [the bug](http://b/292235113) for more details. The upgraded NodeJS uses a newer NPM that doesn't complain about when being run as root.
I tested it out by in a local kokoro container and `--dry-run` flag–the tarball builds correctly:
```
npm notice                                                                                                                                   
npm notice package: pprof@3.3.0                                                                                                              
npm notice === Tarball Contents ===                                                                                                          
npm notice 11.4kB  LICENSE …
```
> chore: fix publish.sh to work with kokoro

- .github/workflows/ci.yaml
- README.md
- system-test/system_test.sh
Expand test support for node versions up to 20. Drop support for other non-LTS versions (odd numbered). Node 21 is not passing tests right now https://github.com/google/pprof-nodejs/issues/283, so I will hold off on that for now.
> chore: update supported node versions to 14, 16, 18, and 20

- package-lock.json
- package.json
- ts/test/test-heap-profiler.ts
- ts/third_party/cloud-debug-nodejs/src/agent/io/scanner.ts
Potentially breaking change as typescript compilation output is not guaranteed to be compatible across major versions.
This combines https://github.com/google/pprof-nodejs/pull/285 and https://github.com/google/pprof-nodejs/pull/266 together. I fixed a few type errors from the upgrade. Specific versions copied from [package.json in cloud-profiler-nodejs downstream](https://github.com/googleapis/cloud-profiler-nodejs/blob/c057bf125255c6b0d264e6ba05a9931f11890832/package.json#L67)
> chore(deps)!: update typescript to v5 and gts to v5

- package-lock.json
- package.json
- system-test/Dockerfile.linux
- system-test/Dockerfile.node-alpine
- system-test/busybench/src/busybench.ts
Updates golang versions and pins pprof dependency for system tests.
`pprof` updated the minimum go requirement which caused the system to fail which were running on golang1.21.
> chore: update golang version and pin dependencies

- .github/workflows/ci.yaml
The npm version coming with Node 14 in Github Actions is v6 which does not support lockfile v3 checked into this repo:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
```
which results in non-hermetic build (see https://github.com/google/pprof-nodejs/pull/297). This PR upgrades npm to the newest version supported in Node 14, which understands the lockfile to pull in exact dependencies.
> chore: fix CI to use newer npm on node 14

- package-lock.json
- package.json
This PR upgrades `nan` to version 2.22, ensuring compatibility on NodeJS 21 and greater.
The main culprit when building `pprof` was `SetAccessor` being renamed, see here: https://github.com/nodejs/nan/commit/6bd62c9a0004339d5d1e18a945c84929d0f6b808
`npm run test`: ✅ 
`system-test/system_test.sh`: ✅
> chore: upgrade nodejs/nan to 2.22
